apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: datadelivery-kafka-rest-proxy
  name: datadelivery-kafka-rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadelivery-kafka-rest-proxy
  template:
    metadata:
      labels:
        app: datadelivery-kafka-rest-proxy
    spec:
      containers:
        - image: confluentinc/cp-kafka-rest:$(IMAGE_TAG) # TODO: Paremetrize tag
          name: cp-kafka-rest-proxy
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  key: KAFKA_REST_BOOTSTRAP_SERVERS
                  name: datadelivery-kafka-rest-proxy
            - name: KAFKA_REST_LISTENERS
              value: "http://0.0.0.0:8082"
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: "http://datadelivery-schema-registry:8081"
            - name: KAFKA_REST_CLIENT_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_REST_CLIENT_SASL_MECHANISM
              value: PLAIN
            - name: KAFKA_REST_CLIENT_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  key: KAFKA_REST_CLIENT_SASL_JAAS_CONFIG
                  name: datadelivery-kafka-rest-proxy
