apiVersion: v1
kind: Secret
metadata:
  name: datadelivery-kafka-rest-proxy
type: Opaque
stringData:
  KAFKA_REST_BOOTSTRAP_SERVERS: "pkc-e8mp5.eu-west-1.aws.confluent.cloud:9092"
  KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$(KAFKA_KEY)\" password=\"$(KAFKA_SECRET)\";
