apiVersion: v1
kind: Secret
metadata:
  name: datadelivery-kafka-rest-proxy
type: Opaque
stringData:
  KAFKA_REST_BOOTSTRAP_SERVERS: "$(KAFKA_BOOTSTRAP_SERVERS)"
  KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$(KAFKA_SASL_USERNAME)\" password=\"$(KAFKA_SASL_PASSWORD)\";
